#!/usr/bin/env python3
import os
import datetime
import subprocess
import glob

# ==========================================
# CONFIGURATION
# ==========================================
NAS_WIKI_DIR = "/mnt/ADAMA-Shared/GodModeData/Wikis"
REPO_URL = "git@github.com:URseismology/OlugbojiLab-Wiki.git"
LOCAL_REPO_DIR = os.path.expanduser("~/OlugbojiLab-Wiki")

DISCLAIMER = """![AI Generated](https://img.shields.io/badge/AI-Generated-blue)

> [!WARNING]
> **AI Hallucination Disclaimer**
> This Wiki was automatically generated by Large Language Models (`DeepSeek-Coder-V2` & `Qwen2.5-72B`) to accelerate onboarding. While structurally accurate, it may occasionally hallucinate specific function calls, variable names, or execution commands (e.g., pseudo-MATLAB commands). Always cross-reference the suggested workflows with the actual source code.
> 
> *For more details on how this was generated, see [0_AI_Generation_Process](0_AI_Generation_Process.md)*

---
"""

def get_download_link(project_name):
    return f"""
---
## 📦 Download Codebase
The complete physical codebase for this project is hosted securely on the Lab NAS.
* **NAS URL:** [https://repovibranium.synology.me:5001/](https://repovibranium.synology.me:5001/)
* **File Station Path:** `/ADAMA-Shared/GodModeData/CodeBaseFull/`
* **Search For:** `{project_name}_codebase_*.tar.gz`
"""

PROCESS_DOC = """# The AI Generation Process

To manage the massive scale of the lab's codebase without causing AI context window explosions (Out Of Memory errors), we developed a custom 2-node architecture:

## 1. The HPC Mapper (`roverBckUp.py`)
Running on the **Bluehive HPC Cluster**, this script recursively scans the entire `/scratch/tolugboj_lab` directory. It safely bypasses massive generic libraries (like Anaconda environments), extracts only the structural source code files (`.m`, `.py`, `.sh`, etc.), packages them into `tar.gz` files, and pushes them directly to the Synology NAS.

* **[Download roverBckUp.py](scripts/roverBckUp.py)**

## 2. The AI Synthesizer (`AIBot-WikiCrafter.py`)
Running on our local dual-GPU inference server (`inferencelocal`), an infinite background daemon polls the NAS for new tarballs. 
It uses a **Recursive Map-Reduce** strategy:
1. **File Map:** It reads every single script individually and asks `DeepSeek-Coder-V2` to generate a 3-sentence summary of its inputs, outputs, and purpose.
2. **Folder Reduce:** It combines the file summaries of a single folder and asks `Qwen2.5-72B` to synthesize a folder-level summary.
3. **Subsystem Bubble-up:** It recursively bubbles these folder summaries up the directory tree until it reaches the root.
4. **Final Synthesis:** `Qwen2.5-72B` takes the massive hierarchical summary and writes the comprehensive Wiki you are reading now.

* **[Download AIBot-WikiCrafter.py](scripts/AIBot-WikiCrafter.py)**

## 3. The GitHub Publisher (`AIBot-GitHubPublisher.py`)
A cron job runs weekly to parse the raw NAS Wikis, inject these disclaimers, format the direct NAS download links, and automatically push the updates to this GitHub repository.

* **[Download AIBot-GitHubPublisher.py](scripts/AIBot-GitHubPublisher.py)**
"""

def run_cmd(cmd, cwd=None):
    print(f"Running: {cmd}")
    res = subprocess.run(cmd, shell=True, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if res.returncode != 0:
        print(f"Error executing {cmd}:\n{res.stderr}")
    return res.returncode == 0

def setup_repo():
    if not os.path.exists(LOCAL_REPO_DIR):
        print(f"Cloning repository {REPO_URL}...")
        run_cmd(f"git clone {REPO_URL} {LOCAL_REPO_DIR}")
    else:
        print("Pulling latest changes...")
        run_cmd("git pull origin main", cwd=LOCAL_REPO_DIR)

def generate_wikis():
    projects = []
    
    auto_dir = os.path.join(LOCAL_REPO_DIR, "Auto_Generated_Wikis")
    os.makedirs(auto_dir, exist_ok=True)
    
    if not os.path.exists(NAS_WIKI_DIR):
        print(f"Error: {NAS_WIKI_DIR} does not exist.")
        return projects
        
    for item in os.listdir(NAS_WIKI_DIR):
        proj_dir = os.path.join(NAS_WIKI_DIR, item)
        if os.path.isdir(proj_dir):
            home_md = os.path.join(proj_dir, "Home.md")
            if os.path.exists(home_md):
                projects.append(item)
                
                with open(home_md, "r", encoding="utf-8") as f:
                    content = f.read()
                
                new_content = DISCLAIMER + content + get_download_link(item)
                
                out_path = os.path.join(auto_dir, f"{item}.md")
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(new_content)
                print(f"Generated {item}.md")
                
    return sorted(projects)

def generate_index(projects):
    auto_dir = os.path.join(LOCAL_REPO_DIR, "Auto_Generated_Wikis")
    os.makedirs(auto_dir, exist_ok=True)
    readme_path = os.path.join(auto_dir, "README.md")
    
    lines = ["# 📚 URseismology Lab Codebase Wikis", ""]
    lines.append("> Welcome to the automatically generated documentation repository for the Olugboji Lab. ")
    lines.append("> Please read the [AI Generation Process & Disclaimer](0_AI_Generation_Process.md) before using this code.")
    lines.append("")
    lines.append("## 🗂️ Available Projects")
    
    for p in projects:
        lines.append(f"- [{p}]({p}.md)")
        
    lines.append("")
    lines.append(f"*Last automatically updated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Generated README.md")

import shutil
def generate_process_doc():
    auto_dir = os.path.join(LOCAL_REPO_DIR, "Auto_Generated_Wikis")
    os.makedirs(auto_dir, exist_ok=True)
    proc_path = os.path.join(auto_dir, "0_AI_Generation_Process.md")
    with open(proc_path, "w", encoding="utf-8") as f:
        f.write(PROCESS_DOC)
    print("Generated 0_AI_Generation_Process.md")
    
    # Copy scripts into the repo
    scripts_dir = os.path.join(LOCAL_REPO_DIR, "scripts")
    os.makedirs(scripts_dir, exist_ok=True)
    
    scripts_to_copy = ["roverBckUp.py", "AIBot-WikiCrafter.py", "AIBot-GitHubPublisher.py", "AIBot-WikiFormatter.py"]
    for s in scripts_to_copy:
        src = os.path.join(os.path.expanduser("~"), s)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(scripts_dir, s))
            print(f"Copied {s} to repo/scripts/")
        else:
            print(f"Warning: {src} not found, could not copy.")

def push_to_github():
    run_cmd("git add .", cwd=LOCAL_REPO_DIR)
    # Check if there are changes
    res = subprocess.run("git status --porcelain", shell=True, cwd=LOCAL_REPO_DIR, stdout=subprocess.PIPE, text=True)
    if not res.stdout.strip():
        print("No changes to commit.")
        return
        
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    run_cmd(f'git commit -m "Auto-update wikis {timestamp}"', cwd=LOCAL_REPO_DIR)
    
    # We assume 'main' is the default branch
    run_cmd("git branch -M main", cwd=LOCAL_REPO_DIR)
    print("Pushing to GitHub...")
    run_cmd("git push -u origin main", cwd=LOCAL_REPO_DIR)

def format_wikis():
    print("Running AIBot-WikiFormatter...")
    formatter_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "AIBot-WikiFormatter.py")
    if os.path.exists(formatter_path):
        run_cmd(f"python3 {formatter_path}")
    else:
        print("Formatter not found, skipping...")

def main():
    print("Starting AIBot-GitHubPublisher...")
    format_wikis()
    setup_repo()
    projects = generate_wikis()
    if projects:
        generate_index(projects)
        generate_process_doc()
        push_to_github()
    print("Finished.")

if __name__ == "__main__":
    main()
